from abc import ABC, abstractmethod
from typing import Any

class CRUD(ABC):
    @abstractmethod
    def create(self, *args, **kwargs) -> None: ...
    @abstractmethod
    def read(self) -> Any: ...
    @abstractmethod
    def update(self, *args, **kwargs) -> None: ...
    @abstractmethod
    def delete(self, *args, **kwargs) -> None: ...